<?xml version="1.0" encoding="UTF-8"?><testrun name="TaskControllerTest" project="tasks-backend" tests="4" started="4" failures="0" errors="1" ignored="0">
  <testsuite name="br.ce.wcaquino.taskbackend.controller.TaskControllerTest" time="0.002">
    <testcase name="naoDeveSalvarTarefaSemDescricao" classname="br.ce.wcaquino.taskbackend.controller.TaskControllerTest" time="0.001">
      <error>br.ce.wcaquino.taskbackend.utils.ValidationException: Fill the task description
	at br.ce.wcaquino.taskbackend.controller.TaskController.save(TaskController.java:34)
	at br.ce.wcaquino.taskbackend.controller.TaskControllerTest.naoDeveSalvarTarefaSemDescricao(TaskControllerTest.java:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

</error>
    </testcase>
    <testcase name="naoDeveSalvarTarefaSemData" classname="br.ce.wcaquino.taskbackend.controller.TaskControllerTest" time="0.0"/>
    <testcase name="deveSalvarTarefaComSucesso" classname="br.ce.wcaquino.taskbackend.controller.TaskControllerTest" time="0.0"/>
    <testcase name="naoDeveSalvarTarefaComDataPassada" classname="br.ce.wcaquino.taskbackend.controller.TaskControllerTest" time="0.0"/>
  </testsuite>
</testrun>
